project_id = "fuori"

[auth]
site_url = "http://127.0.0.1:4174"
additional_redirect_urls = ["http://127.0.0.1:4174", "http://localhost:4174"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
